[package]
name = "rust_client"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.1"
prost = "0.6.1"
prost-types = "0.6.1"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.1.1"